name: miniaudio
description: a library for play audio cross patform.
version: 0.0.0 
homepage: https://github.com/azkadev/miniaudio/wiki
repository: https://github.com/azkadev/miniaudio.git
issue_tracker: https://github.com/azkadev/miniaudio/issues

environment:
  sdk: '>=2.17.5 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies: 
  ffi: ^2.0.1 
